### ISSUE TITLE
Create element in default position

### ISSUE THREAD

**Issue by csaura** [swanandp/acts_as_list#103]
When I try create a new element in the default position create it at the bottom of the list.

Example:

```
*********************************
* Tasks
*********************************
* id
* name
* position , NOT NULL, DEFAULT 0
*********************************

class Task
 acts_as_list  top_of_list: 0, add_new_at: :bottom
end

# existing elements
task position: 0 id: 20
task position: 1 id: 35
task position: 2 id: 15
task position: 3 id: 14
task position: 4 id: 16
task position: 5 id: 17
task position: 6 id: 18

# create new element
task = Task.create(position: 0, name: 'I want to be at the top')

task.position => 7 # but I wanted to create it at position 0
```

How can I create a new element forcing the default position?

**Comment by brendon** [comment]
Joining in late, but this sounds like two different scopes to me.

`acts_as_list scope: [:task_list, :status], add_new_at: :top`

or something like that. Still that wouldn't allow for the complex logic about where in the list an item in the `complete` status scope should go when it joins that scope. Callbacks are probably the answer, or manually specifying the position after checking the existing entries.

I'll close this for now since it's had no action for a while, but I'm happy to discuss it further if you want.
