### ISSUE TITLE
Make insert_at respect position when creating a new record

### ISSUE THREAD

**Issue by goalaleo** [swanandp/acts_as_list#287]
**Request**

Currently the position of a new record uses the `add_new_at` value. Is it possible to make new records respect the parameter given to `insert_at`.

Example:
```
class Person < ActiveRecord::Base
    has_many :dogs
end

class Dog < ActiveRecord::Base
    belongs_to :person
    acts_as_list scope: :person
end

# irb
person = Person.new
person.dogs << Dog.new(name: "First Dog")
new_dog = Dog.new(person: person, name: "Second Dog")

# imo this should set new_dog's position to 1, and update existing ones as needed
new_dog.insert_at(1)

new_dog.position

# expected
=> 1
# got
=> 2
```

**Comment by brendon** [comment]
Hi @goalaleo, you can actually just pass the position you want into the `.new` method:

new_dog = Dog.new(person: person, name: "Second Dog", position: 1)

Acts As List will shuffle things around so that your new object has that position and the others don't. `insert_at` is for existing records either in this scope or any other scope.

I hope that helps. I'll close this for now but let me know if you think I've missed the point.

**Comment by goalaleo** [comment]
@brendon ok, thanks 👍 ! I still feel like the naming of `insert_at` is a bit misleading, as it does work on new instances, does a literal insert DB operation, but doesn't actually insert the record to the given position :/ Either way, great gem!

**Comment by brendon** [comment]
@goalaleo, yes you're right. It should probably be named `reposition_at` or something like that though that would break the api and I think this method has been around since the beginning. @swanandp, did you have any thoughts on this one?

**Comment by brendon** [comment]
Thanks @DanielHeath :) Would you be keen to put together a small PR for that? I'd be happy to merge that for you.

**Comment by DanielHeath** [comment]
Makes sense to me, will do.
